// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: spot_instrument.proto

package spot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"` //Флаг активности рынка. true = рынок торгуется, false = приостановлен.
	DeleteAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_spot_instrument_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_spot_instrument_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Market) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Market) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRoles     []string               `protobuf:"bytes,1,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"` //у пользователя может быть несколько ролей.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_instrument_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_instrument_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsRequest) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

// Список рынков.
type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"` //возвращаем множество рынков, а не один.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_instrument_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_instrument_proto_rawDescGZIP(), []int{2}
}

func (x *ViewMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

var File_spot_instrument_proto protoreflect.FileDescriptor

const file_spot_instrument_proto_rawDesc = "" +
	"\n" +
	"\x15spot_instrument.proto\x12\x0fspot_instrument\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x127\n" +
	"\tdelete_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeleteAt\"3\n" +
	"\x12ViewMarketsRequest\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x01 \x03(\tR\tuserRoles\"H\n" +
	"\x13ViewMarketsResponse\x121\n" +
	"\amarkets\x18\x01 \x03(\v2\x17.spot_instrument.MarketR\amarkets2q\n" +
	"\x15SpotInstrumentService\x12X\n" +
	"\vViewMarkets\x12#.spot_instrument.ViewMarketsRequest\x1a$.spot_instrument.ViewMarketsResponseB3Z1gRPC_progect/exchange-system/generation/spot;spotb\x06proto3"

var (
	file_spot_instrument_proto_rawDescOnce sync.Once
	file_spot_instrument_proto_rawDescData []byte
)

func file_spot_instrument_proto_rawDescGZIP() []byte {
	file_spot_instrument_proto_rawDescOnce.Do(func() {
		file_spot_instrument_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_instrument_proto_rawDesc), len(file_spot_instrument_proto_rawDesc)))
	})
	return file_spot_instrument_proto_rawDescData
}

var file_spot_instrument_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_instrument_proto_goTypes = []any{
	(*Market)(nil),                // 0: spot_instrument.Market
	(*ViewMarketsRequest)(nil),    // 1: spot_instrument.ViewMarketsRequest
	(*ViewMarketsResponse)(nil),   // 2: spot_instrument.ViewMarketsResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_spot_instrument_proto_depIdxs = []int32{
	3, // 0: spot_instrument.Market.delete_at:type_name -> google.protobuf.Timestamp
	0, // 1: spot_instrument.ViewMarketsResponse.markets:type_name -> spot_instrument.Market
	1, // 2: spot_instrument.SpotInstrumentService.ViewMarkets:input_type -> spot_instrument.ViewMarketsRequest
	2, // 3: spot_instrument.SpotInstrumentService.ViewMarkets:output_type -> spot_instrument.ViewMarketsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spot_instrument_proto_init() }
func file_spot_instrument_proto_init() {
	if File_spot_instrument_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_instrument_proto_rawDesc), len(file_spot_instrument_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spot_instrument_proto_goTypes,
		DependencyIndexes: file_spot_instrument_proto_depIdxs,
		MessageInfos:      file_spot_instrument_proto_msgTypes,
	}.Build()
	File_spot_instrument_proto = out.File
	file_spot_instrument_proto_goTypes = nil
	file_spot_instrument_proto_depIdxs = nil
}
