syntax = "proto3";

package spot.v1;

option go_package = "grpc-exchange/gen/spot;spotv1";

import "common/money.proto";
import "common/decimal.proto";

import "google/protobuf/timestamp.proto";

service SpotInstrumentService {
  rpc ViewMarkets(ViewMarketsRequest) returns (ViewMarketsResponse);
  rpc GetMarket(GetMarketRequest) returns (Market);
}

message Market{
  string market_id = 1;
  string name = 2; 
  string base_asset = 3;            // Базовая валюта (например, "BTC")
  string quote_asset = 4;           // Котируемая валюта (например, "USD")
  bool enabled = 5;                 // Активен ли рынок
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp deleted_at = 7; // null если не удален
  
  common.v1.Money min_price = 8;    // Минимальная цена
  common.v1.Money max_price = 9;    // Максимальная цена
  common.v1.Decimal min_quantity = 10; // Минимальное количество
  common.v1.Decimal max_quantity = 11; // Максимальное количество
}

//getMarket, фильтр? +

message ViewMarketsRequest {
  repeated string user_roles = 1; //у пользователя может быть несколько ролей. 
}

//Список рынков.
message ViewMarketsResponse {
  repeated Market markets = 1; //возвращаем множество рынков, а не один.
}

message GetMarketRequest {
  string market_id = 1;
}

//command enum - роли(статусы) реализовывать их отдельно в order