syntax = "proto3";

package order_instrument;

option go_package = "gRPC_progect/exchange-system/generation/order;order";

import "google/protobuf/timestamp.proto";

service OrderService {
    rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse);
    rpc GetOrderStatus(GetOrderStatusRequest) returns (GetOrderStatusResponse);
}

message Order {
  string id = 1;
  string user_id = 2;
  string market_id = 3;
  string order_type = 4;
  double price = 5;
  int64 quantity = 6; //Кол-во
  string status = 7;
  google.protobuf.Timestamp created_at = 8;
}

message CreateOrderRequest {
  string user_id = 1;
  string market_id = 2;
  string order_type = 3;
  double price = 4;
  int64 quantity = 5;
  repeated string user_roles = 6;
}

message CreateOrderResponse{
  string order_id = 1;
  string status = 2;
}

message GetOrderStatusRequest {
  string order_id = 1;
  string user_id = 2;
}

message GetOrderStatusResponse{
  string status = 1;
}
